### ISSUE TITLE
type declaration for typescript not working properly. 

### ISSUE THREAD

**Issue by danirdd92** [maptiler/maptiler-sdk-js#46]
Issue is very easy to reproduce, no type definition coming from the package.
I've tested with svelte and vanilla-ts using vite.
installed `@maptiler/sdk": "1.1.2` , I can't seem to get type declarations working.
overriding the backslash in the name allows me to step into dist and import type declarations directly but breaks during trans/compile time.
I'm using latest pnpm as package manager if that makes a difference.

Has anybody else encountered this?

**Comment by danirdd92** [comment]
Hi exactly, both coming with from the vite cli boilerplate.

I do have a suspicion regarding the cause which is the name of the package `@maptiler/sdk`
I believe the backslash doesn't register properly as a name alias but as path which breaks some existing preconceptions that either vs-code or typescript have regarding the location of the declaration files.

**Comment by jonathanlurie** [comment]
Hello @danirdd92 ,
I am not super familiar with Svelte, so I used the Vanilla TS code sample from ViteJS (powered by Stackblitz) and I could create an example that works well. Please find it here: https://stackblitz.com/edit/vitejs-vite-r14wrj?file=readme.md

The issue was in the default `tsconfig.json` of the ViteJS project, they use a somewhat legacy/non-official `"moduleResolution": "bundler",` that I replaced with a more common `"moduleResolution": "node",`. This tells TS how to resolve the modules. It's a bit verbose but you can find more info about this here: https://www.typescriptlang.org/docs/handbook/module-resolution.html

The slash `/` character is generally not an issue and is often used as a way to create a logic of namespace within the NPM ecosystem. For example, at MapTiler, we try to publish all our official packages with the prefix `@maptiler/`. You can see this a lot with companies, but it's less frequent for non-affiliated individuals.

You're 100% correct, MapLibre GL, Mapbox GL, and MapTiler SDK do look very similar and that is for historical reasons. The project started 10 years ago and was originally created by Mapbox. After some years of development, they decided that after a certain version, their library will no longer be published as open source (even though the source is available on GitHub, the license of Mapbox GL JS is no longer open). At this moment, there was already a fairly large ecosystem of open-source developers that were using it and were creating all sorts of plugins for it, and they decided to join forces and fork the very last version of Mapbox GL JS that was published under an open source license, and they called this fork MapLibre GL JS. For some years now, MapLibre GL JS is being maintained by a very active community and is diverging more and more from Mapbox GL JS.

As per MapTiler SDK, this is not a fork of MapLibre GL JS, this is an extension, so it has exactly the same capabilities, and on top of this, we add a smoother compatibility layer with MapTiler Cloud, as well as some nice helper, functions to make the developer experience more enjoyable. For example, with MapTiler SDK, you don't really have to think about what is the URL of the raster tiles to add 3D terrain or how to configure it, this is done internally and you just have to construct your map instance with `terrain: true`. That's just an example.

I do understand the confusion and I will pass the message to our documentation team, I am sure we can improve this point!

**Comment by danirdd92** [comment]
Thank you very much @jonathanlurie !

Your help is much appreciated both with the ts issue and the history of all the mapping libs mentioned above.

kind regards,
Daniel.

**Comment by PolynomialTim** [comment]
I ran into something similar while writing a project using `@maptiler/sdk` also scaffolded with `create vite` (React/TS template).

Similar to what @jonathanlurie  said, changing `tsconfig.json:compilerOptions.moduleResolution` from `bundle` to `node`  also resolved the issues I was seeing locally.

While looking for answers about the errors I was seeing, I stumbled on some long discussions and a reference to [arethetypeswrong.github.io](https://arethetypeswrong.github.io/?p=%40maptiler%2Fsdk%401.1.2) for checking NPM package exported TS types. Their [Github repo](https://github.com/arethetypeswrong/arethetypeswrong.github.io) has additional documentation about common causes for each flagged type of error.


Outside my realm of expertise, but might be helpful in fixing the type exports in `@maptiler/sdk` so that others don't run into the same issue in the future.
